name: CommitMessage

on:
  push:
    branches: ["develop", "release/1.6"]
  pull_request:
    branches: ["develop", "release/1.6"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: uptownaravi/verify-commit-message-action@v2
      with:
          regex: '(?i)^(VF-[0-9]{2,}|NO\-JIRA)\b'
